import { addTypeTemplate, type Resolver } from '@nuxt/kit';
import { relative, resolve } from 'pathe';

export const registerTypeTemplates = (resolver: Resolver) => {
  addTypeTemplate({
    filename: 'types/sanctum.d.ts',
    getContents: ({ nuxt }) => {
      const { buildDir } = nuxt.options;
      const getRelativePath = (path: string) =>
        relative(resolve(buildDir, './types'), resolver.resolve(path));
      return `// Generated by nuxt-auth-sanctum module
import type { SanctumAppConfig } from './runtime/types' '${getRelativePath('./runtime/types')}';

declare module 'nuxt/schema' {
  interface AppConfig {
    laravelSanctum?: SanctumAppConfig;
  }
  interface AppConfigInput {
    laravelSanctum?: SanctumAppConfig;
  }
}

declare module '@nuxt/schema' {
  interface AppConfig {
    laravelSanctum?: SanctumAppConfig;
  }
  interface AppConfigInput {
    laravelSanctum?: SanctumAppConfig;
  }
}

export {};`;
    },
  });
};
